import { IAuthApi, ApiResponse } from './types';
import { User, Location, Review, Tag, VerifyStatus } from '../types/schema';
import axios from 'axios';

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api';

export const apiClient = axios.create({
    baseURL: API_BASE,
    headers: {
        'Content-Type': 'application/json'
    }
});

apiClient.interceptors.request.use((config) => {
    const token = localStorage.getItem('token');
    if (token && config.headers) {
        config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
});

apiClient.interceptors.response.use(
    (response) => response,
    (error) => {
        if (error.response && error.response.status === 401) {
            localStorage.removeItem('token');
            // Check if we are not already on login page
            if (window.location.pathname !== '/login') {
                window.location.href = '/login';
            }
        }
        return Promise.reject(error);
    }
);


export const realAuthApi: IAuthApi = {
    login: async (email, password): Promise<ApiResponse<User>> => {
        try {
            const response = await apiClient.post('/auth/login', { email, password });
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as User, message: error.response?.data?.message || 'Login failed' };
        }
    },
    register: async (user): Promise<ApiResponse<User>> => {
        try {
            // Note: role and created_at are generated by server
            const payload = {
                email: user.email,
                username: user.username,
                password: user.password,
                full_name: user.full_name,
                birth_year: user.birth_year,
                interests: user.interests,
                province: user.province
            };
            const response = await apiClient.post('/auth/register', payload);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as User, message: error.response?.data?.message || 'Registration failed' };
        }
    },
    logout: async () => {
        try {
            await apiClient.post('/auth/logout');
        } catch (error) {
            console.error('Logout error', error);
        }
    },
    getCurrentUser: async () => {
        return { success: false, data: {} as User, message: 'Not implemented without JWT' };
    }
};

export const realUserApi = {
    getProfile: async (id: number): Promise<ApiResponse<User>> => {
        try {
            const response = await apiClient.get(`/users/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as User, message: error.response?.data?.message || 'Fetch failed' };
        }
    },
    updateProfile: async (id: number, data: Partial<User>): Promise<ApiResponse<User>> => {
        try {
            const payload = {
                full_name: data.full_name,
                phone_number: data.phone_number,
                avatar_url: data.avatar_url,
                gender: (data.gender as any) === '' ? undefined : data.gender,
                birth_year: data.birth_year,
                nationality: data.nationality
            };
            const response = await apiClient.put(`/users/${id}`, payload);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as User, message: error.response?.data?.message || 'Update failed' };
        }
    },
    getAll: async (): Promise<ApiResponse<User[]>> => {
        try {
            const response = await apiClient.get('/users');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch users' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/users/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Delete failed' };
        }
    },
    updateAvatar: async (id: number, avatarUrl: string): Promise<ApiResponse<User>> => {
        try {
            const response = await apiClient.post(`/users/${id}/avatar`, { avatar_url: avatarUrl });
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as User, message: error.response?.data?.message || 'Avatar update failed' };
        }
    },
    getInterests: async (id: number): Promise<ApiResponse<number[]>> => {
        try {
            const response = await apiClient.get(`/users/${id}/interests`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [], message: 'Failed' };
        }
    },
    saveInterests: async (id: number, categoryIds: number[]): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.post(`/users/${id}/interests`, categoryIds);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Failed' };
        }
    }
};

export const realLocationApi = {
    getAll: async (): Promise<ApiResponse<Location[]>> => {
        try {
            const response = await apiClient.get('/locations');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch' };
        }
    },
    getById: async (id: number): Promise<ApiResponse<Location>> => {
        try {
            const response = await apiClient.get(`/locations/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Failed to fetch' };
        }
    },
    search: async (query: string): Promise<ApiResponse<Location[]>> => {
        try {
            const response = await apiClient.get(`/locations/search?query=${encodeURIComponent(query)}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Search failed' };
        }
    },
    getPaginated: async (params: any): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.get('/locations/search/paginated', { params });
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Pagination failed' };
        }
    },
    getProvinces: async (): Promise<ApiResponse<string[]>> => {
        try {
            const response = await apiClient.get('/locations/provinces');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [], message: 'Failed to fetch provinces' };
        }
    },
    create: async (location: Partial<Location>): Promise<ApiResponse<Location>> => {
        try {
            const response = await apiClient.post('/locations', location);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Create failed' };
        }
    },
    getRecommendations: async (userId: number, lat?: number, lng?: number): Promise<ApiResponse<Location[]>> => {
        try {
            let url = `/locations/recommendations?userId=${userId}`;
            if (lat !== undefined && lng !== undefined) url += `&lat=${lat}&lng=${lng}`;
            const response = await apiClient.get(url);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch recommendations' };
        }
    },
    getSimilar: async (id: number, topN: number = 5): Promise<ApiResponse<Location[]>> => {
        try {
            const response = await apiClient.get(`/locations/${id}/recommendations?topN=${topN}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed' };
        }
    },
    getPersonalizedRecommendations: async (lat?: number, lng?: number, hour?: number, weather?: string): Promise<ApiResponse<Location[]>> => {
        try {
            let url = `/locations/recommendations/context`;
            const params = [];
            if (lat !== undefined) params.push(`lat=${lat}`);
            if (lng !== undefined) params.push(`lng=${lng}`);
            if (hour !== undefined) params.push(`hour=${hour}`);
            if (weather !== undefined) params.push(`weather=${weather}`);
            if (params.length > 0) url += `?${params.join('&')}`;

            const response = await apiClient.get(url);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch smart recommendations' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/locations/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Delete failed' };
        }
    },
    update: async (id: number, location: Partial<Location>): Promise<ApiResponse<Location>> => {
        try {
            const response = await apiClient.put(`/locations/${id}`, location);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Update failed' };
        }
    }
};

export const realReviewApi = {
    getByLocation: async (locationId: number): Promise<ApiResponse<Review[]>> => {
        try {
            const response = await apiClient.get(`/reviews/location/${locationId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch reviews' };
        }
    },
    addReview: async (review: Partial<Review>): Promise<ApiResponse<Review>> => {
        try {
            // Mapping exactly matching the API needs
            const payload = {
                user_id: review.user_id,
                location_id: review.location_id,
                rating: review.rating,
                comment: review.comment,
                images_json: review.images_json,
                visit_date: review.visit_date,
                trip_type: review.trip_type
            };
            const response = await apiClient.post('/reviews', payload);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Failed to submit review. Ensures you have an approved visit first!' };
        }
    },
    getAll: async (): Promise<ApiResponse<Review[]>> => {
        try {
            const response = await apiClient.get('/reviews');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/reviews/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Delete failed' };
        }
    },
    updateStatus: async (id: number, status: VerifyStatus): Promise<ApiResponse<Review>> => {
        try {
            const response = await apiClient.put(`/reviews/${id}/status`, { status });
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as Review, message: error.response?.data?.message || 'Update status failed' };
        }
    },
    updateReview: async (id: number, review: Partial<Review>): Promise<ApiResponse<Review>> => {
        try {
            const response = await apiClient.put(`/reviews/${id}`, review);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as Review, message: error.response?.data?.message || 'Update review failed' };
        }
    }
};

export const realVisitApi = {
    requestVisit: async (userId: number, locationId: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.post(`/visits/request?userId=${userId}&locationId=${locationId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Request failed' };
        }
    },
    updateStatus: async (requestId: number, status: 'PENDING' | 'APPROVED' | 'REJECTED' | 'COMPLETED'): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.put(`/visits/${requestId}/status`, { status });
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Update failed' };
        }
    },
    getAllRequests: async (): Promise<ApiResponse<any[]>> => {
        try {
            const response = await apiClient.get(`/visits`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch' };
        }
    },
    canUserReview: async (userId: number, locationId: number): Promise<ApiResponse<boolean>> => {
        try {
            const response = await apiClient.get(`/visits/can-review?userId=${userId}&locationId=${locationId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: false, message: error.response?.data?.message };
        }
    },
    getUserRequests: async (userId: number): Promise<ApiResponse<any[]>> => {
        try {
            const response = await apiClient.get(`/visits/user/${userId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch history' };
        }
    }
};

export const realUploadApi = {
    image: async (file: File): Promise<ApiResponse<any>> => {
        try {
            const formData = new FormData();
            formData.append('file', file);

            const response = await apiClient.post('/upload/image', formData, {
                headers: {
                    'Content-Type': 'multipart/form-data'
                }
            });
            // Result is { success: true, url: "..." }
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Upload failed' };
        }
    }
};

export const realBehaviorApi = {
    logAction: async (log: any): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.post('/behavior/log', log);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Logging failed' };
        }
    }
};

export const realTagApi = {
    getAll: async (): Promise<ApiResponse<Tag[]>> => {
        try {
            const response = await apiClient.get('/tags');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [] as any, message: error.response?.data?.message || 'Failed to fetch tags' };
        }
    },
    create: async (tag: Partial<Tag>): Promise<ApiResponse<Tag>> => {
        try {
            const response = await apiClient.post('/tags', tag);
            return response.data;
        } catch (error: any) {
            return { success: false, data: {} as any, message: error.response?.data?.message || 'Failed to create tag' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/tags/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: error.response?.data?.message || 'Delete failed' };
        }
    }
};

export const realCategoryApi = {
    getAll: async (): Promise<ApiResponse<any[]>> => {
        try {
            const response = await apiClient.get('/categories');
            return response.data;
        } catch (error: any) {
            return { success: false, data: [], message: 'Failed to fetch categories' };
        }
    },
    create: async (category: any): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.post('/categories', category);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Failed to create category' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/categories/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Delete failed' };
        }
    }
};

export const realFavoriteApi = {
    toggle: async (userId: number, locationId: number): Promise<ApiResponse<boolean>> => {
        try {
            const response = await apiClient.post(`/favorites/toggle?userId=${userId}&locationId=${locationId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: false, message: 'Toggle favorite failed' };
        }
    },
    getByUser: async (userId: number): Promise<ApiResponse<any[]>> => {
        try {
            const response = await apiClient.get(`/favorites/user/${userId}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: [], message: 'Failed to fetch favorites' };
        }
    }
};

export const realBlogApi = {
    getAll: async (params?: any): Promise<ApiResponse<any[]>> => {
        try {
            const response = await apiClient.get('/blogs', { params });
            return response.data;
        } catch (error: any) {
            return { success: false, data: [], message: 'Failed to fetch blogs' };
        }
    },
    getById: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.get(`/blogs/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Failed to fetch blog' };
        }
    },
    create: async (blog: any): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.post('/blogs', blog);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Failed to create blog' };
        }
    },
    update: async (id: number, blog: any): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.put(`/blogs/${id}`, blog);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Failed to update blog' };
        }
    },
    delete: async (id: number): Promise<ApiResponse<any>> => {
        try {
            const response = await apiClient.delete(`/blogs/${id}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: null, message: 'Delete failed' };
        }
    }
};

export const realNewsletterApi = {
    subscribe: async (email: string): Promise<ApiResponse<string>> => {
        try {
            const response = await apiClient.post('/newsletter/subscribe', { email });
            return response.data;
        } catch (error: any) {
            return { success: false, data: '', message: error.response?.data?.message || 'Subscription failed' };
        }
    },
    getStatus: async (email: string): Promise<ApiResponse<boolean>> => {
        try {
            const response = await apiClient.get(`/newsletter/status?email=${email}`);
            return response.data;
        } catch (error: any) {
            return { success: false, data: false, message: 'Failed to fetch status' };
        }
    },
    unsubscribe: async (email: string): Promise<ApiResponse<string>> => {
        try {
            const response = await apiClient.post('/newsletter/unsubscribe', { email });
            return response.data;
        } catch (error: any) {
            return { success: false, data: '', message: error.response?.data?.message || 'Unsubscription failed' };
        }
    }
};
