spring:
  application:
    name: recommendation
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/travel_recommendation}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    type: redis
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:lydung853@gmail.com}
    password: ${MAIL_APP_PASSWORD:default-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
      enabled: true

cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://214292353552372:-0LUsrI3h2LII2oYO6s9ylU9Sco@dlh7xxigk}

logging:
  level:
    org.springframework.security: INFO

ai:
  service:
    base-url: ${AI_SERVICE_BASE_URL:http://localhost:8000}
